version: '3.4'

services:
 rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"


 microservicecarreservation:
    image: ${DOCKER_REGISTRY-}microservicecarreservation
    build:
      context: .
      dockerfile: App/MicroserviceCarReservation/Dockerfile
    depends_on: 
      - rabbitmq

 microservicehotelreservation:
    image: ${DOCKER_REGISTRY-}microservicehotelreservation
    build:
      context: .
      dockerfile: App/MicroserviceHotelReservation/Dockerfile
    depends_on: 
      - rabbitmq

 microservicegateway:
    image: ${DOCKER_REGISTRY-}microservicegateway
    ports:
      - "10002:80"
    build:
      context: .
      dockerfile: App/MicroserviceGateway/Dockerfile
    depends_on: 
      - rabbitmq
 

